/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AnalysisId = bigint;
export interface AnalysisInput {
  'imageQuality' : Quality,
  'reportText' : string,
  'modality' : Modality,
  'triageStatus' : TriageStatus,
  'timestamp' : Time,
  'patientName' : string,
  'findings' : Array<string>,
  'image' : ExternalBlob,
  'confidenceScores' : Array<number>,
}
export interface AnalysisRecord {
  'id' : AnalysisId,
  'imageQuality' : Quality,
  'userId' : UserId,
  'reportText' : string,
  'modality' : Modality,
  'triageStatus' : TriageStatus,
  'timestamp' : Time,
  'patientName' : string,
  'findings' : Array<string>,
  'image' : ExternalBlob,
  'confidenceScores' : Array<number>,
}
export type ExternalBlob = Uint8Array;
export type Modality = { 'ct' : null } |
  { 'mri' : null };
export type Quality = { 'good' : null } |
  { 'poor' : null };
export type Time = bigint;
export type TriageStatus = { 'normal' : null } |
  { 'critical' : null };
export type UserId = Principal;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAnalysis' : ActorMethod<[AnalysisId], AnalysisRecord>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyAnalyses' : ActorMethod<[], Array<AnalysisRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAnalysis' : ActorMethod<[AnalysisInput], AnalysisId>,
  'timeToText' : ActorMethod<[Time], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];