/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AnalysisId = IDL.Nat;
export const Quality = IDL.Variant({ 'good' : IDL.Null, 'poor' : IDL.Null });
export const UserId = IDL.Principal;
export const Modality = IDL.Variant({ 'ct' : IDL.Null, 'mri' : IDL.Null });
export const TriageStatus = IDL.Variant({
  'normal' : IDL.Null,
  'critical' : IDL.Null,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AnalysisRecord = IDL.Record({
  'id' : AnalysisId,
  'imageQuality' : Quality,
  'userId' : UserId,
  'patientPhone' : IDL.Text,
  'reportText' : IDL.Text,
  'modality' : Modality,
  'triageStatus' : TriageStatus,
  'timestamp' : Time,
  'patientName' : IDL.Text,
  'findings' : IDL.Vec(IDL.Text),
  'image' : ExternalBlob,
  'confidenceScores' : IDL.Vec(IDL.Float64),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const AnalysisInput = IDL.Record({
  'imageQuality' : Quality,
  'patientPhone' : IDL.Text,
  'reportText' : IDL.Text,
  'modality' : Modality,
  'triageStatus' : TriageStatus,
  'timestamp' : Time,
  'patientName' : IDL.Text,
  'findings' : IDL.Vec(IDL.Text),
  'image' : ExternalBlob,
  'confidenceScores' : IDL.Vec(IDL.Float64),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAnalysis' : IDL.Func([AnalysisId], [AnalysisRecord], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyAnalyses' : IDL.Func([], [IDL.Vec(AnalysisRecord)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAnalysis' : IDL.Func([AnalysisInput], [AnalysisId], []),
  'timeToText' : IDL.Func([Time], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AnalysisId = IDL.Nat;
  const Quality = IDL.Variant({ 'good' : IDL.Null, 'poor' : IDL.Null });
  const UserId = IDL.Principal;
  const Modality = IDL.Variant({ 'ct' : IDL.Null, 'mri' : IDL.Null });
  const TriageStatus = IDL.Variant({
    'normal' : IDL.Null,
    'critical' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AnalysisRecord = IDL.Record({
    'id' : AnalysisId,
    'imageQuality' : Quality,
    'userId' : UserId,
    'patientPhone' : IDL.Text,
    'reportText' : IDL.Text,
    'modality' : Modality,
    'triageStatus' : TriageStatus,
    'timestamp' : Time,
    'patientName' : IDL.Text,
    'findings' : IDL.Vec(IDL.Text),
    'image' : ExternalBlob,
    'confidenceScores' : IDL.Vec(IDL.Float64),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const AnalysisInput = IDL.Record({
    'imageQuality' : Quality,
    'patientPhone' : IDL.Text,
    'reportText' : IDL.Text,
    'modality' : Modality,
    'triageStatus' : TriageStatus,
    'timestamp' : Time,
    'patientName' : IDL.Text,
    'findings' : IDL.Vec(IDL.Text),
    'image' : ExternalBlob,
    'confidenceScores' : IDL.Vec(IDL.Float64),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAnalysis' : IDL.Func([AnalysisId], [AnalysisRecord], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyAnalyses' : IDL.Func([], [IDL.Vec(AnalysisRecord)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAnalysis' : IDL.Func([AnalysisInput], [AnalysisId], []),
    'timeToText' : IDL.Func([Time], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };